(()=>{'use strict';
const $=id=>document.getElementById(id),S={file:null,doc:null,shapes:[],parts:[],active:new Set(),mode:'original',nest:null};
const E={file:$('fileInput'),drop:$('dropzone'),meta:$('fileMeta'),analyze:$('analyzeBtn'),nest:$('nestBtn'),reset:$('resetBtn'),w:$('sheetWidth'),h:$('sheetHeight'),margin:$('margin'),gap:$('gap'),rotate:$('allowRotate'),svg:$('preview'),empty:$('emptyState'),list:$('partsList'),count:$('partCount'),shape:$('shapeStat'),contour:$('contourStat'),parts:$('partsStat'),sheets:$('sheetsStat'),usage:$('usageStat'),title:$('viewTitle'),note:$('viewNote')};
const NS='http://www.w3.org/2000/svg',EPS=1e-7;
const I=()=>[1,0,0,1,0,0];
function mul(a,b){return[a[0]*b[0]+a[2]*b[1],a[1]*b[0]+a[3]*b[1],a[0]*b[2]+a[2]*b[3],a[1]*b[2]+a[3]*b[3],a[0]*b[4]+a[2]*b[5]+a[4],a[1]*b[4]+a[3]*b[5]+a[5]]}
function ap(m,p){return{x:m[0]*p.x+m[2]*p.y+m[4],y:m[1]*p.x+m[3]*p.y+m[5]}}
function xf(n){const x=[...n.children].find(c=>c.tagName==='XForm');if(!x)return I();const v=x.textContent.trim().split(/\s+/).map(Number);return v.length===6&&v.every(Number.isFinite)?v:I()}
function box(ps){let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const p of ps){minX=Math.min(minX,p.x);minY=Math.min(minY,p.y);maxX=Math.max(maxX,p.x);maxY=Math.max(maxY,p.y)}return{minX,minY,maxX,maxY,width:maxX-minX,height:maxY-minY}}
function area(ps){let a=0;for(let i=0,j=ps.length-1;i<ps.length;j=i++)a+=ps[j].x*ps[i].y-ps[i].x*ps[j].y;return a/2}
function pip(p,poly){let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){const a=poly[i],b=poly[j];if(((a.y>p.y)!==(b.y>p.y))&&p.x<(b.x-a.x)*(p.y-a.y)/((b.y-a.y)||EPS)+a.x)inside=!inside}return inside}
function contains(a,b){return a.minX<=b.minX+EPS&&a.minY<=b.minY+EPS&&a.maxX>=b.maxX-EPS&&a.maxY>=b.maxY-EPS}
function verts(t){const out=[];if(!t)return out;const r=/V\s*(-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[-+]?\d+)?)\s+(-?(?:\d+(?:\.\d*)?|\.\d+)(?:e[-+]?\d+)?)/gi;let m;while((m=r.exec(t)))out.push({x:+m[1],y:+m[2]});return out}
function defs(root){const v=new Map(),p=new Map();for(const s of root.querySelectorAll('Shape')){const vi=s.getAttribute('VertID'),pi=s.getAttribute('PrimID'),vn=[...s.children].find(n=>n.tagName==='VertList'),pn=[...s.children].find(n=>n.tagName==='PrimList');if(vi&&vn?.textContent.trim()&&!v.has(vi))v.set(vi,vn.textContent.trim());if(pi&&pn?.textContent.trim()&&!p.has(pi))p.set(pi,pn.textContent.trim())}return{v,p}}
function cuts(root){S.active.clear();for(const c of [...root.children].filter(n=>n.tagName==='CutSetting')){const o={};for(const x of c.children)o[x.tagName]=x.getAttribute('Value');const i=+o.index;if(Number.isFinite(i)&&o.doOutput!=='0')S.active.add(i)}}
function walk(shape,parent,d,out,id){const type=shape.getAttribute('Type')||'',world=mul(parent,xf(shape));if(type==='Group'){const ch=[...shape.children].find(n=>n.tagName==='Children');if(ch)for(const s of [...ch.children].filter(n=>n.tagName==='Shape'))walk(s,world,d,out,id);return}let ps=[],closed=false;if(type==='Path'){const vi=shape.getAttribute('VertID'),pi=shape.getAttribute('PrimID'),vn=[...shape.children].find(n=>n.tagName==='VertList'),pn=[...shape.children].find(n=>n.tagName==='PrimList'),vt=vn?.textContent.trim()||(vi?d.v.get(vi):'')||'',pt=pn?.textContent.trim()||(pi?d.p.get(pi):'')||'';ps=verts(vt);closed=/closed/i.test(pt)||/(?:L|B)\d+\s+0\s*$/i.test(pt)}else if(type==='Rect'){const w=+shape.getAttribute('W')||0,h=+shape.getAttribute('H')||0;ps=[{x:-w/2,y:-h/2},{x:w/2,y:-h/2},{x:w/2,y:h/2},{x:-w/2,y:h/2}];closed=true}else return;ps=ps.map(p=>ap(world,p));if(ps.length<2)return;const b=box(ps),a=closed?Math.abs(area(ps)):0,cut=+shape.getAttribute('CutIndex');out.push({id:id.n++,type,cut,active:S.active.has(cut),closed,points:ps,bbox:b,area:a})}
function flatten(root){const d=defs(root),out=[],id={n:1};for(const s of [...root.children].filter(n=>n.tagName==='Shape'))walk(s,I(),d,out,id);return out}
function detect(shapes){const cs=shapes.filter(s=>s.active&&s.closed&&s.points.length>=3&&s.area>.01),parent=new Map();for(const inn of cs){const p={x:(inn.bbox.minX+inn.bbox.maxX)/2,y:(inn.bbox.minY+inn.bbox.maxY)/2};let best=null;for(const out of cs){if(out.id===inn.id||out.area<=inn.area||!contains(out.bbox,inn.bbox)||!pip(p,out.points))continue;if(!best||out.area<best.area)best=out}if(best)parent.set(inn.id,best.id)}const by=new Map(cs.map(x=>[x.id,x]));function root(id){const seen=new Set();while(parent.has(id)&&!seen.has(id)){seen.add(id);id=parent.get(id)}return id}const groups=new Map();for(const c of cs){const r=root(c.id);if(!groups.has(r))groups.set(r,[]);groups.get(r).push(c)}return[...groups].map(([rid,m])=>{const outer=by.get(rid),inners=m.filter(x=>x.id!==rid);return{rootId:rid,outer,inners,members:m,bbox:outer.bbox,area:outer.area,material:Math.max(0,outer.area-inners.reduce((s,x)=>s+x.area,0))}}).sort((a,b)=>b.area-a.area).map((p,i)=>({...p,id:i+1}))}
function norm(ps){const b=box(ps);return{points:ps.map(p=>({x:p.x-b.minX,y:p.y-b.minY})),width:b.width,height:b.height}}
function orient(part,rot){const n=norm(part.outer.points);if(!rot)return{...n,rot:false};const r=n.points.map(p=>({x:-p.y,y:p.x})),q=norm(r);return{...q,rot:true}}
function seg(a,b,c,d){const cr=(p,q,r)=>(q.x-p.x)*(r.y-p.y)-(q.y-p.y)*(r.x-p.x),x=cr(a,b,c),y=cr(a,b,d),z=cr(c,d,a),w=cr(c,d,b);return((x>EPS&&y<-EPS)||(x<-EPS&&y>EPS))&&((z>EPS&&w<-EPS)||(z<-EPS&&w>EPS))}
function overlap(a,b){const A=box(a),B=box(b);if(A.maxX<=B.minX+EPS||B.maxX<=A.minX+EPS||A.maxY<=B.minY+EPS||B.maxY<=A.minY+EPS)return false;for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++)if(seg(a[i],a[(i+1)%a.length],b[j],b[(j+1)%b.length]))return true;return pip(a[0],b)||pip(b[0],a)}
function distPointSeg(p,a,b){const vx=b.x-a.x,vy=b.y-a.y,l=vx*vx+vy*vy;if(l<EPS)return Math.hypot(p.x-a.x,p.y-a.y);let t=((p.x-a.x)*vx+(p.y-a.y)*vy)/l;t=Math.max(0,Math.min(1,t));return Math.hypot(p.x-(a.x+t*vx),p.y-(a.y+t*vy))}
function distance(a,b,stop=Infinity){if(overlap(a,b))return 0;let d=Infinity;for(let i=0;i<a.length;i++)for(const p of b){d=Math.min(d,distPointSeg(p,a[i],a[(i+1)%a.length]));if(d<stop)return d}for(let i=0;i<b.length;i++)for(const p of a){d=Math.min(d,distPointSeg(p,b[i],b[(i+1)%b.length]));if(d<stop)return d}return d}
function translate(ps,x,y){return ps.map(p=>({x:p.x+x,y:p.y+y}))}
function anchors(placed,w,h,m,g){const xs=new Set([m]),ys=new Set([m]);for(const p of placed){xs.add(p.bbox.maxX+g);xs.add(p.bbox.minX-w-g);ys.add(p.bbox.maxY+g);ys.add(p.bbox.minY-h-g)}const a=[];for(const y of ys)for(const x of xs)if(x>=m-EPS&&y>=m-EPS)a.push({x,y});return a.sort((u,v)=>u.y-v.y||u.x-v.x)}
function place(part,placed,s){let best=null;for(const o of [orient(part,false),...(s.rotate?[orient(part,true)]:[])]){for(const a of anchors(placed,o.width,o.height,s.margin,s.gap)){if(a.x+o.width>s.w-s.margin+EPS||a.y+o.height>s.h-s.margin+EPS)continue;const poly=translate(o.points,a.x,a.y),b=box(poly);let ok=true;for(const q of placed){if(overlap(poly,q.poly)||(s.gap>0&&distance(poly,q.poly,s.gap)<s.gap-EPS)){ok=false;break}}if(ok){const score=(a.y+o.height)*s.w+a.x;if(!best||score<best.score)best={x:a.x,y:a.y,poly,bbox:b,rot:o.rot,score};break}}}return best}
function pack(parts,cmp,s){const sheets=[],overflow=[];for(const part of parts.slice().sort(cmp)){let done=false;for(let i=0;i<sheets.length&&!done;i++){const p=place(part,sheets[i],s);if(p){sheets[i].push({...p,part,sheet:i});done=true}}if(!done){const sh=[],p=place(part,sh,s);if(p){sh.push({...p,part,sheet:sheets.length});sheets.push(sh)}else overflow.push(part)}}return{sheets,overflow,height:sheets.reduce((n,sh)=>n+(sh.length?Math.max(...sh.map(p=>p.bbox.maxY)):0),0)}}
function nesting(parts,s){const cs=[(a,b)=>b.area-a.area,(a,b)=>Math.max(b.bbox.width,b.bbox.height)-Math.max(a.bbox.width,a.bbox.height),(a,b)=>b.bbox.height-a.bbox.height||(b.area-a.area),(a,b)=>b.bbox.width-a.bbox.width||(b.area-a.area)];return cs.map(c=>pack(parts,c,s)).sort((a,b)=>a.overflow.length-b.overflow.length||a.sheets.length-b.sheets.length||a.height-b.height)[0]}
function svg(tag,attrs={}){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);return n}
function pts(ps){return ps.map(p=>`${p.x.toFixed(3)},${p.y.toFixed(3)}`).join(' ')}
function clear(){while(E.svg.firstChild)E.svg.removeChild(E.svg.firstChild)}
function memberLocal(m,part,rot){const base=part.bbox;let ps=m.points.map(p=>({x:p.x-base.minX,y:p.y-base.minY}));if(!rot)return ps;const outer=part.outer.points.map(p=>({x:p.x-base.minX,y:p.y-base.minY})).map(p=>({x:-p.y,y:p.x})),ob=box(outer);return ps.map(p=>({x:-p.y-ob.minX,y:p.x-ob.minY}))}
function renderOriginal(){S.mode='original';clear();if(!S.shapes.length)return;const b=box(S.shapes.flatMap(s=>s.points)),pad=Math.max(8,Math.max(b.width,b.height)*.03);E.svg.setAttribute('viewBox',`${b.minX-pad} ${b.minY-pad} ${b.width+2*pad} ${b.height+2*pad}`);for(const sh of S.shapes){const part=S.parts.find(p=>p.members.some(m=>m.id===sh.id));let cl='inactive';if(sh.active)cl=part&&part.rootId===sh.id?'outer':'inner';E.svg.appendChild(svg(sh.closed?'polygon':'polyline',{points:pts(sh.points),class:`shape ${cl}`,'data-shape-id':sh.id}))}for(const p of S.parts){const t=svg('text',{x:(p.bbox.minX+p.bbox.maxX)/2,y:(p.bbox.minY+p.bbox.maxY)/2,class:'part-label'});t.textContent=p.id;E.svg.appendChild(t)}E.title.textContent='Original plassering';E.note.textContent=`${fm(b.width)} × ${fm(b.height)} mm tegneområde · ${S.parts.length} sannsynlige deler`;E.sheets.textContent='–';E.usage.textContent='–';E.reset.disabled=true}
function renderNest(r,s){S.mode='nest';S.nest=r;clear();const sg=18,totalH=r.sheets.length*s.h+Math.max(0,r.sheets.length-1)*sg;E.svg.setAttribute('viewBox',`-8 -8 ${s.w+16} ${Math.max(totalH,s.h)+16}`);r.sheets.forEach((sh,si)=>{const oy=si*(s.h+sg);E.svg.appendChild(svg('rect',{x:0,y:oy,width:s.w,height:s.h,rx:1.5,class:'sheet'}));const lab=svg('text',{x:4,y:oy+9,class:'sheet-label'});lab.textContent=`Plate ${si+1} · ${s.w} × ${s.h} mm`;E.svg.appendChild(lab);for(const q of sh){for(const m of q.part.members){const pp=translate(memberLocal(m,q.part,q.rot),q.x,q.y+oy),cl=m.id===q.part.rootId?'outer':'inner';E.svg.appendChild(svg('polygon',{points:pts(pp),class:`shape ${cl}`,'data-part-id':q.part.id}))}const t=svg('text',{x:(q.bbox.minX+q.bbox.maxX)/2,y:(q.bbox.minY+q.bbox.maxY)/2+oy,class:'part-label'});t.textContent=`${q.part.id}${q.rot?'↻':''}`;E.svg.appendChild(t)}});const mat=S.parts.reduce((n,p)=>n+p.material,0),cap=Math.max(1,r.sheets.length)*s.w*s.h;E.sheets.textContent=r.sheets.length;E.usage.textContent=`${Math.min(100,100*mat/cap).toFixed(1)} %`;E.title.textContent='Forslag til nesting';E.note.textContent=r.overflow.length?`${r.overflow.length} del(er) fikk ikke plass`:`Heuristisk plassering over ${r.sheets.length} plate${r.sheets.length===1?'':'r'}`;E.reset.disabled=false}
function list(){E.list.innerHTML='';E.count.textContent=S.parts.length;if(!S.parts.length){E.list.textContent='Ingen deler oppdaget.';return}for(const p of S.parts){const r=document.createElement('div');r.className='part-row';r.innerHTML=`<span class="num">${p.id}</span><span><strong>${fm(p.bbox.width)} × ${fm(p.bbox.height)} mm</strong><br><span class="dims">ca. ${Math.round(p.material).toLocaleString('nb-NO')} mm²</span></span><span class="holes">${p.inners.length} innv.</span>`;r.onclick=()=>highlight(p.id);E.list.appendChild(r)}}
function highlight(id){for(const n of E.svg.querySelectorAll('.shape'))n.classList.remove('highlight');if(S.mode==='original'){const p=S.parts.find(x=>x.id===id);if(!p)return;const ids=new Set(p.members.map(x=>String(x.id)));for(const n of E.svg.querySelectorAll('[data-shape-id]'))if(ids.has(n.getAttribute('data-shape-id')))n.classList.add('highlight')}else for(const n of E.svg.querySelectorAll(`[data-part-id="${id}"]`))n.classList.add('highlight')}
function analyze(){const root=S.doc?.documentElement;if(!root)return;cuts(root);S.shapes=flatten(root);S.parts=detect(S.shapes);E.shape.textContent=S.shapes.length;E.contour.textContent=S.shapes.filter(s=>s.active&&s.closed).length;E.parts.textContent=S.parts.length;list();renderOriginal();E.nest.disabled=!S.parts.length}
function settings(){const s={w:+E.w.value,h:+E.h.value,margin:Math.max(0,+E.margin.value||0),gap:Math.max(0,+E.gap.value||0),rotate:E.rotate.checked};if(!(s.w>0&&s.h>0))throw Error('Platens bredde og høyde må være større enn 0.');if(s.margin*2>=s.w||s.margin*2>=s.h)throw Error('Kantmarginen er for stor.');return s}
async function load(file){if(!file)return;const text=await file.text(),doc=new DOMParser().parseFromString(text,'application/xml');if(doc.querySelector('parsererror')||doc.documentElement.tagName!=='LightBurnProject')throw Error('Filen ser ikke ut som et gyldig LightBurn-prosjekt.');S.file=file;S.doc=doc;E.meta.textContent=`${file.name} · ${(file.size/1024).toFixed(1)} kB · LightBurn ${doc.documentElement.getAttribute('AppVersion')||'?'}`;E.meta.classList.remove('muted');E.empty.style.display='none';E.analyze.disabled=false;analyze()}
const fm=n=>Number.isFinite(n)?n.toFixed(n>=100?0:1):'–';
E.file.onchange=e=>load(e.target.files?.[0]).catch(x=>alert(x.message));E.analyze.onclick=analyze;E.nest.onclick=()=>{try{const s=settings();renderNest(nesting(S.parts,s),s)}catch(x){alert(x.message)}};E.reset.onclick=renderOriginal;E.drop.ondragover=e=>{e.preventDefault();E.drop.classList.add('drag')};E.drop.ondragleave=()=>E.drop.classList.remove('drag');E.drop.ondrop=e=>{e.preventDefault();E.drop.classList.remove('drag');load(e.dataTransfer.files?.[0]).catch(x=>alert(x.message))};
})();